import unittest
from importlib.resources import files


class WebAssetsTests(unittest.TestCase):
    def test_offline_map_and_controls_are_packaged(self):
        root = files("botw_companion.web")
        self.assertGreater(len(root.joinpath("hyrule-map.webp").read_bytes()), 100_000)
        self.assertGreater(len(root.joinpath("map-tiles", "z1", "0_0.webp").read_bytes()), 10_000)
        self.assertGreater(len(root.joinpath("map-tiles", "z2", "0_0.webp").read_bytes()), 10_000)
        self.assertGreater(len(root.joinpath("map-tiles", "z3", "12_10.webp").read_bytes()), 10_000)
        html = root.joinpath("index.html").read_text(encoding="utf-8")
        script = root.joinpath("app.js").read_text(encoding="utf-8")
        css = root.joinpath("metrics.css").read_text(encoding="utf-8")
        self.assertIn('id="mapStage"', html)
        self.assertIn('id="runtimePlatform"', html)
        self.assertIn('id="savePreview"', html)
        self.assertIn('id="saveCaption"', html)
        self.assertIn('id="saveSlotTitle"', html)
        self.assertIn('id="mapTiles"', html)
        self.assertIn('id="geoPath"', html)
        self.assertIn('id="itemDetails"', html)
        self.assertNotIn("Référentiel du 100 % BOTW + DLC", html)
        self.assertNotIn('id="coverage"', html)
        self.assertNotIn("function renderCoverage", script)
        self.assertIn('/armor.css', html)
        self.assertIn("function worldPoint", script)
        self.assertIn("function renderMapTiles", script)
        self.assertIn("MAP_TILE_LEVELS", script)
        self.assertIn('tile.addEventListener("error"', script)
        self.assertIn("2 / level.density", script)
        self.assertIn("border: 0", css)
        self.assertIn("function renderDetails", script)
        self.assertIn("function renderSavePreview", script)
        self.assertIn("/api/save-caption?revision=", script)
        self.assertIn("function closeDetails", script)
        self.assertIn("selectedId = null", script)
        self.assertIn("renderMap(filtered())", script)
        self.assertIn("prochaine_amelioration", script)
        self.assertIn("geo_points", script)
        self.assertIn("data-geo-center", script)
        self.assertIn("marker waypoint", script)
        self.assertIn("guideCard", script)
        self.assertIn("geoPath", script)
        self.assertIn("function renderFilterNav", script)
        self.assertIn("selectedTypes", script)
        self.assertIn("if (!filtersInitialized) {\n        filtersInitialized = true;", script)
        self.assertIn("filterGroup", root.joinpath("armor.css").read_text(encoding="utf-8"))
        self.assertIn('value="info"', html)
        self.assertIn('value="master_trials"', html)
        self.assertIn('value="champions_ballad"', html)
        self.assertIn('value="free_update"', html)
        self.assertIn("function originMatches", script)
        self.assertIn('id="manualScore"', html)
        self.assertIn('id="toggleManualReview"', html)
        self.assertIn('id="manualReviewSearch"', html)
        self.assertIn('id="manualReviewCategory"', html)
        self.assertIn('id="manualReviewList"', html)
        self.assertIn('value="mixed"', html)
        self.assertIn("function saveManual", script)
        self.assertIn("function saveManualById", script)
        self.assertIn("function renderManualReview", script)
        self.assertIn("function uncheckManualFromReview", script)
        self.assertIn("/api/manual/import", script)
        self.assertIn("manualTracking", root.joinpath("armor.css").read_text(encoding="utf-8"))
        self.assertIn("manualReviewItem", root.joinpath("armor.css").read_text(encoding="utf-8"))
        self.assertIn("saveCaptionFrame", root.joinpath("armor.css").read_text(encoding="utf-8"))
        self.assertIn("Solution détaillée", script)
        self.assertIn("guideSources", script)
        self.assertIn("function frenchSourceName", script)
        self.assertIn("Zelda Wiki - article sur", script)
        self.assertIn("guideDetail", root.joinpath("armor.css").read_text(encoding="utf-8"))
        self.assertIn('id="routePlanner"', html)
        self.assertIn('id="toggleRoute"\n                    aria-expanded="false"', html)
        self.assertIn('<div id="routeBody" hidden>', html)
        self.assertIn('id="addFiltered"', html)
        self.assertIn('/route_planner.js', html)
        self.assertIn('id="routeSessionSelect"', html)
        self.assertIn('id="importRouteJson"', html)
        self.assertIn("/api/routes/import", script)
        self.assertIn("/api/backup/export", script)
        self.assertIn("/api/backup/import", script)
        self.assertIn("/api/preferences", script)
        self.assertIn("migrateBrowserPreferences", script)
        self.assertIn("/api/catalog", script)
        self.assertIn("/api/detail/", script)
        self.assertIn('id="showMoreResults"', script)
        self.assertIn("if (data.changed)", script)
        self.assertIn("await load(false)", script)
        self.assertIn("function optimizeCurrentRoute", script)
        self.assertIn("ROUTE_STORAGE_KEY", script)
        self.assertIn("plannerWaypoint", root.joinpath("armor.css").read_text(encoding="utf-8"))
        self.assertIn('id="syncStatus"', html)
        self.assertIn('id="syncInterval"', html)
        self.assertIn('id="pauseSync"', html)
        self.assertIn("function checkSync", script)
        self.assertIn("/api/sync", script)
        self.assertIn('id="completionProfile"', html)
        self.assertIn("function selectedCompletionScore", script)
        self.assertIn("PROFILE_KEY", script)
        self.assertIn('value="amiibo"', html)
        self.assertIn('id="gameMode"', html)
        self.assertIn('value="all"', html)
        self.assertIn("Tous les modes (averti)", html)
        self.assertIn('id="location"', html)
        self.assertIn('value="coordinates_missing"', html)
        self.assertIn('value="no_natural_location"', html)
        self.assertIn('value="interior_only"', html)
        self.assertIn('id="filterScopeNotice"', html)
        self.assertIn("function gameModeMatches", script)
        self.assertIn("function locationMatches", script)
        self.assertIn("function renderFilterScopeNotice", script)
        self.assertIn("coverage_note", script)
        self.assertIn("interiorPoints", script)
        self.assertIn('id="bloodMoonPanel"', html)
        self.assertIn('id="bloodMoonCountdown"', html)
        self.assertIn('id="bloodMoonThreshold"', html)
        self.assertIn('id="bloodMoonScheduled"', html)
        self.assertIn('id="bloodMoonMeasuredAt"', html)
        self.assertIn("function renderBloodMoon", script)
        self.assertIn("active_seconds_until_event", script)
        self.assertIn("active_seconds_until_scheduled", script)
        self.assertIn("scopedByType", script)
        self.assertIn("function isCompletedShrineWithRemainingChest", script)
        self.assertIn("function filterGroupsForDisplay", script)
        self.assertIn('"sanctuaires_termines_coffres_restants"', script)
        self.assertIn("filterProgress", root.joinpath("armor.css").read_text(encoding="utf-8"))
        self.assertIn(".item > .dot", root.joinpath("armor.css").read_text(encoding="utf-8"))
        self.assertIn('id="quitCompanion"', html)
        self.assertIn('id="dsuControl"', html)
        self.assertIn('id="dsuEngineLabel"', html)
        self.assertIn('id="toggleDsu"', html)
        self.assertIn('id="dsuDiagnostic"', html)
        self.assertIn('id="dsuQuality"', html)
        self.assertIn("function renderDsu", script)
        self.assertIn("function renderDsuDiagnostic", script)
        self.assertIn("quality-excellent", root.joinpath("armor.css").read_text(encoding="utf-8"))
        self.assertIn("quality-recalibration", root.joinpath("armor.css").read_text(encoding="utf-8"))
        self.assertIn("function loadRuntimePlatform", script)
        self.assertIn("runtimePlatform.label", script)
        self.assertIn("runtimePlatform.relaunch_hint", script)
        self.assertIn("runtimePlatform.native_dsu_engine", script)
        self.assertNotIn("Clique à nouveau sur l’icône du Dock", script)
        self.assertIn("function copyText", script)
        self.assertIn('document.execCommand("copy")', script)
        self.assertNotIn("navigator.clipboard.writeText(\n", script)
        self.assertIn("function refreshDsu", script)
        self.assertIn("function toggleDsu", script)
        self.assertIn("/api/dsu/", script)
        self.assertIn('$("#dsuControl").title = [', script)
        self.assertIn("dsuControl", root.joinpath("armor.css").read_text(encoding="utf-8"))
        self.assertIn("/api/heartbeat", script)
        self.assertIn("/api/shutdown", script)
        self.assertIn("document.hidden", script)
        self.assertIn("Math.max(180, syncInterval)", script)
        self.assertIn("visibilitychange", script)

        layout_css = root.joinpath("style.css").read_text(encoding="utf-8")
        self.assertIn("@media (min-width: 1001px)", layout_css)
        self.assertIn(".listPanel {\n        height: auto;", layout_css)
        self.assertIn("overflow-y: auto;", layout_css)
        self.assertIn("overflow-x: hidden;", layout_css)
        self.assertNotIn("row.scrollIntoView", script)
        self.assertIn("list.getBoundingClientRect()", script)
        self.assertIn("list.scrollTo({", script)


if __name__ == "__main__":
    unittest.main()
